# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sahil Kharb
email: sahil@phoenixx.me
description: My conversations with neural networks and design patterns.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://phoenixx.me" # the base hostname & protocol for your site
twitter_username: sahil_kharb
github_username:  bitfurry

# Build settings
#markdown: kramdown
markdown: redcarpet
